### ISSUE TITLE
Could not create class edu.mit.csail.sdg.alloy4compiler.parser.CompUtil

### ISSUE THREAD

**Issue by ph3b** [HiroakiMikami/atom-alloy#17]
Hi,

I'm getting an error when trying to run execute, compile. I'm guessing this is because I am missing some of the dependencies (perhaps the entire compiler?). Could you point me in the right directions as to where to get them?

Thank you and have a nice day.

```
Error: Could not create class edu.mit.csail.sdg.alloy4compiler.parser.CompUtil
java.lang.NoClassDefFoundError: edu/mit/csail/sdg/alloy4compiler/parser/CompUtil
Caused by: java.lang.ClassNotFoundException: edu.mit.csail.sdg.alloy4compiler.parser.CompUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at Java.java.import (/Users/userfolder/.atom/packages/atom-alloy/node_modules/java/lib/nodeJavaBridge.js:227:20)
    at Alloy.module.exports.Alloy.initializeIfNecessary (/Users/userfolder/.atom/packages/atom-alloy/lib/alloy.coffee:29:23)
    at Alloy.module.exports.Alloy.compile (/Users/userfolder/.atom/packages/atom-alloy/lib/alloy.coffee:78:6)
    at Object.compile (/Users/userfolder/.atom/packages/atom-alloy/lib/atom-alloy.coffee:102:12)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-alloy:compile (/Users/userfolder/.atom/packages/atom-alloy/lib/atom-alloy.coffee:55:86)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by HiroakiMikami** [comment]
Sorry my reply is late.

I think that alloy was not installed in your PC.
Please download a jar file from [this page](http://alloy.mit.edu/alloy/download.html), then put the path of the jar file (e.g, `${HOME}/Downloads/alloy-4.2.jar`) to this package configuration.
![ss](https://cloud.githubusercontent.com/assets/5582874/22969117/93dcbf98-f3b0-11e6-89b1-602ce9a244d0.png)
